use crate::cpu::{CPU, CycleResult};
use common::snes_address::SnesAddress;

use crate::instrs::{
    arithmetic::*,
    branches::*,
    flags::*,
    jumps::*,
    loads::*,
    stores::*,
    uncategorised::*,
};

pub(crate) struct InstrCycle(pub fn(&mut CPU) -> (CycleResult, InstrCycle));

impl From<fn(&mut CPU) -> (CycleResult, InstrCycle)> for InstrCycle {
    fn from(value: fn(&mut CPU) -> (CycleResult, InstrCycle)) -> Self {
        InstrCycle(value)
    }
}

pub(crate) fn opcode_fetch(cpu: &mut CPU) -> (CycleResult, InstrCycle) {
    cpu.addr_bus = SnesAddress {
        bank: cpu.registers.PB,
        addr: cpu.registers.PC,
    };

    (
        CycleResult::Read,
        InstrCycle(|next_cyc_cpu| (INSTR_CYC1[next_cyc_cpu.data_bus as usize].0)(next_cyc_cpu)),
    )
}

macro_rules! todo_opcode {
    ($oc:tt) => {
        |_| {
            todo!("opcode {:#2x} not yet implemented!", $oc);
        }
    }
}

const INSTR_CYC1: [InstrCycle; 256] = [
    /* 00 */ InstrCycle(todo_opcode!(0x00)),
    /* 01 */ InstrCycle(ora::dxind_cyc1),
    /* 02 */ InstrCycle(todo_opcode!(0x02)),
    /* 03 */ InstrCycle(ora::sr_cyc1),
    /* 04 */ InstrCycle(todo_opcode!(0x04)),
    /* 05 */ InstrCycle(ora::d_cyc1),
    /* 06 */ InstrCycle(todo_opcode!(0x06)),
    /* 07 */ InstrCycle(ora::dindl_cyc1),
    /* 08 */ InstrCycle(todo_opcode!(0x08)),
    /* 09 */ InstrCycle(ora::imm_cyc1),
    /* 0a */ InstrCycle(todo_opcode!(0x0a)),
    /* 0b */ InstrCycle(todo_opcode!(0x0b)),
    /* 0c */ InstrCycle(todo_opcode!(0x0c)),
    /* 0d */ InstrCycle(ora::abs_cyc1),
    /* 0e */ InstrCycle(todo_opcode!(0x0e)),
    /* 0f */ InstrCycle(ora::absl_cyc1),
    /* 10 */ InstrCycle(bpl_cyc1),
    /* 11 */ InstrCycle(ora::dindy_cyc1),
    /* 12 */ InstrCycle(ora::dind_cyc1),
    /* 13 */ InstrCycle(ora::sry_cyc1),
    /* 14 */ InstrCycle(todo_opcode!(0x14)),
    /* 15 */ InstrCycle(ora::dx_cyc1),
    /* 16 */ InstrCycle(todo_opcode!(0x16)),
    /* 17 */ InstrCycle(ora::dindly_cyc1),
    /* 18 */ InstrCycle(clc_cyc1),
    /* 19 */ InstrCycle(ora::absy_cyc1),
    /* 1a */ InstrCycle(todo_opcode!(0x1a)),
    /* 1b */ InstrCycle(todo_opcode!(0x1b)),
    /* 1c */ InstrCycle(todo_opcode!(0x1c)),
    /* 1d */ InstrCycle(ora::absx_cyc1),
    /* 1e */ InstrCycle(todo_opcode!(0x1e)),
    /* 1f */ InstrCycle(ora::abslx_cyc1),
    /* 20 */ InstrCycle(jsr_abs_cyc1),
    /* 21 */ InstrCycle(and::dxind_cyc1),
    /* 22 */ InstrCycle(jsl_cyc1),
    /* 23 */ InstrCycle(and::sr_cyc1),
    /* 24 */ InstrCycle(todo_opcode!(0x24)),
    /* 25 */ InstrCycle(and::d_cyc1),
    /* 26 */ InstrCycle(todo_opcode!(0x26)),
    /* 27 */ InstrCycle(and::dindl_cyc1),
    /* 28 */ InstrCycle(todo_opcode!(0x28)),
    /* 29 */ InstrCycle(and::imm_cyc1),
    /* 2a */ InstrCycle(todo_opcode!(0x2a)),
    /* 2b */ InstrCycle(todo_opcode!(0x2b)),
    /* 2c */ InstrCycle(todo_opcode!(0x2c)),
    /* 2d */ InstrCycle(and::abs_cyc1),
    /* 2e */ InstrCycle(todo_opcode!(0x2e)),
    /* 2f */ InstrCycle(and::absl_cyc1),
    /* 30 */ InstrCycle(bmi_cyc1),
    /* 31 */ InstrCycle(and::dindy_cyc1),
    /* 32 */ InstrCycle(and::dind_cyc1),
    /* 33 */ InstrCycle(and::sry_cyc1),
    /* 34 */ InstrCycle(todo_opcode!(0x34)),
    /* 35 */ InstrCycle(and::dx_cyc1),
    /* 36 */ InstrCycle(todo_opcode!(0x36)),
    /* 37 */ InstrCycle(and::dindly_cyc1),
    /* 38 */ InstrCycle(sec_cyc1),
    /* 39 */ InstrCycle(and::absy_cyc1),
    /* 3a */ InstrCycle(todo_opcode!(0x3a)),
    /* 3b */ InstrCycle(todo_opcode!(0x3b)),
    /* 3c */ InstrCycle(todo_opcode!(0x3c)),
    /* 3d */ InstrCycle(and::absx_cyc1),
    /* 3e */ InstrCycle(todo_opcode!(0x3e)),
    /* 3f */ InstrCycle(and::abslx_cyc1),
    /* 40 */ InstrCycle(todo_opcode!(0x40)),
    /* 41 */ InstrCycle(eor::dxind_cyc1),
    /* 42 */ InstrCycle(todo_opcode!(0x42)),
    /* 43 */ InstrCycle(eor::sr_cyc1),
    /* 44 */ InstrCycle(todo_opcode!(0x44)),
    /* 45 */ InstrCycle(eor::d_cyc1),
    /* 46 */ InstrCycle(todo_opcode!(0x46)),
    /* 47 */ InstrCycle(eor::dindl_cyc1),
    /* 48 */ InstrCycle(todo_opcode!(0x48)),
    /* 49 */ InstrCycle(eor::imm_cyc1),
    /* 4a */ InstrCycle(todo_opcode!(0x4a)),
    /* 4b */ InstrCycle(todo_opcode!(0x4b)),
    /* 4c */ InstrCycle(jmp_abs_cyc1),
    /* 4d */ InstrCycle(eor::abs_cyc1),
    /* 4e */ InstrCycle(todo_opcode!(0x4e)),
    /* 4f */ InstrCycle(eor::absl_cyc1),
    /* 50 */ InstrCycle(bvc_cyc1),
    /* 51 */ InstrCycle(eor::dindy_cyc1),
    /* 52 */ InstrCycle(eor::dind_cyc1),
    /* 53 */ InstrCycle(eor::sry_cyc1),
    /* 54 */ InstrCycle(todo_opcode!(0x54)),
    /* 55 */ InstrCycle(eor::dx_cyc1),
    /* 56 */ InstrCycle(todo_opcode!(0x56)),
    /* 57 */ InstrCycle(eor::dindly_cyc1),
    /* 58 */ InstrCycle(cli_cyc1),
    /* 59 */ InstrCycle(eor::absy_cyc1),
    /* 5a */ InstrCycle(todo_opcode!(0x5a)),
    /* 5b */ InstrCycle(todo_opcode!(0x5b)),
    /* 5c */ InstrCycle(jmp_absl_cyc1),
    /* 5d */ InstrCycle(eor::absx_cyc1),
    /* 5e */ InstrCycle(todo_opcode!(0x5e)),
    /* 5f */ InstrCycle(eor::abslx_cyc1),
    /* 60 */ InstrCycle(rts_cyc1),
    /* 61 */ InstrCycle(adc::dxind_cyc1),
    /* 62 */ InstrCycle(todo_opcode!(0x62)),
    /* 63 */ InstrCycle(adc::sr_cyc1),
    /* 64 */ InstrCycle(stz_d_cyc1),
    /* 65 */ InstrCycle(adc::d_cyc1),
    /* 66 */ InstrCycle(todo_opcode!(0x66)),
    /* 67 */ InstrCycle(adc::dindl_cyc1),
    /* 68 */ InstrCycle(todo_opcode!(0x68)),
    /* 69 */ InstrCycle(adc::imm_cyc1),
    /* 6a */ InstrCycle(todo_opcode!(0x6a)),
    /* 6b */ InstrCycle(rtl_cyc1),
    /* 6c */ InstrCycle(jmp_abs_ind_cyc1),
    /* 6d */ InstrCycle(adc::abs_cyc1),
    /* 6e */ InstrCycle(todo_opcode!(0x6e)),
    /* 6f */ InstrCycle(adc::absl_cyc1),
    /* 70 */ InstrCycle(bvs_cyc1),
    /* 71 */ InstrCycle(adc::dindy_cyc1),
    /* 72 */ InstrCycle(adc::dind_cyc1),
    /* 73 */ InstrCycle(adc::sry_cyc1),
    /* 74 */ InstrCycle(stz_dx_cyc1),
    /* 75 */ InstrCycle(adc::dx_cyc1),
    /* 76 */ InstrCycle(todo_opcode!(0x76)),
    /* 77 */ InstrCycle(adc::dindly_cyc1),
    /* 78 */ InstrCycle(sei_cyc1),
    /* 79 */ InstrCycle(adc::absy_cyc1),
    /* 7a */ InstrCycle(todo_opcode!(0x7a)),
    /* 7b */ InstrCycle(todo_opcode!(0x7b)),
    /* 7c */ InstrCycle(jmp_abs_ind_indx_cyc1),
    /* 7d */ InstrCycle(adc::absx_cyc1),
    /* 7e */ InstrCycle(todo_opcode!(0x7e)),
    /* 7f */ InstrCycle(adc::abslx_cyc1),
    /* 80 */ InstrCycle(bra_cyc1),
    /* 81 */ InstrCycle(sta_dxind_cyc1),
    /* 82 */ InstrCycle(brl_cyc1),
    /* 83 */ InstrCycle(sta_sr_cyc1),
    /* 84 */ InstrCycle(sty_d_cyc1),
    /* 85 */ InstrCycle(sta_d_cyc1),
    /* 86 */ InstrCycle(stx_d_cyc1),
    /* 87 */ InstrCycle(sta_dindl_cyc1),
    /* 88 */ InstrCycle(todo_opcode!(0x88)),
    /* 89 */ InstrCycle(todo_opcode!(0x89)),
    /* 8a */ InstrCycle(todo_opcode!(0x8a)),
    /* 8b */ InstrCycle(todo_opcode!(0x8b)),
    /* 8c */ InstrCycle(sty_abs_cyc1),
    /* 8d */ InstrCycle(sta_abs_cyc1),
    /* 8e */ InstrCycle(stx_abs_cyc1),
    /* 8f */ InstrCycle(sta_absl_cyc1),
    /* 90 */ InstrCycle(bcc_cyc1),
    /* 91 */ InstrCycle(sta_dindy_cyc1),
    /* 92 */ InstrCycle(sta_dind_cyc1),
    /* 93 */ InstrCycle(sta_sry_cyc1),
    /* 94 */ InstrCycle(sty_dx_cyc1),
    /* 95 */ InstrCycle(sta_dx_cyc1),
    /* 96 */ InstrCycle(stx_dy_cyc1),
    /* 97 */ InstrCycle(sta_dindly_cyc1),
    /* 98 */ InstrCycle(todo_opcode!(0x98)),
    /* 99 */ InstrCycle(sta_absy_cyc1),
    /* 9a */ InstrCycle(todo_opcode!(0x9a)),
    /* 9b */ InstrCycle(todo_opcode!(0x9b)),
    /* 9c */ InstrCycle(stz_abs_cyc1),
    /* 9d */ InstrCycle(sta_absx_cyc1),
    /* 9e */ InstrCycle(stz_absx_cyc1),
    /* 9f */ InstrCycle(sta_abslx_cyc1),
    /* a0 */ InstrCycle(ldy_imm_cyc1),
    /* a1 */ InstrCycle(lda_dxind_cyc1),
    /* a2 */ InstrCycle(ldx_imm_cyc1),
    /* a3 */ InstrCycle(lda_sr_cyc1),
    /* a4 */ InstrCycle(ldy_d_cyc1),
    /* a5 */ InstrCycle(lda_d_cyc1),
    /* a6 */ InstrCycle(ldx_d_cyc1),
    /* a7 */ InstrCycle(lda_dindl_cyc1),
    /* a8 */ InstrCycle(todo_opcode!(0xa8)),
    /* a9 */ InstrCycle(lda_imm_cyc1),
    /* aa */ InstrCycle(todo_opcode!(0xaa)),
    /* ab */ InstrCycle(todo_opcode!(0xab)),
    /* ac */ InstrCycle(ldy_abs_cyc1),
    /* ad */ InstrCycle(lda_abs_cyc1),
    /* ae */ InstrCycle(ldx_abs_cyc1),
    /* af */ InstrCycle(lda_absl_cyc1),
    /* b0 */ InstrCycle(bcs_cyc1),
    /* b1 */ InstrCycle(lda_dindy_cyc1),
    /* b2 */ InstrCycle(lda_dind_cyc1),
    /* b3 */ InstrCycle(lda_sry_cyc1),
    /* b4 */ InstrCycle(ldy_dx_cyc1),
    /* b5 */ InstrCycle(lda_dx_cyc1),
    /* b6 */ InstrCycle(ldx_dy_cyc1),
    /* b7 */ InstrCycle(lda_dindly_cyc1),
    /* b8 */ InstrCycle(clv_cyc1),
    /* b9 */ InstrCycle(lda_absy_cyc1),
    /* ba */ InstrCycle(todo_opcode!(0xba)),
    /* bb */ InstrCycle(todo_opcode!(0xbb)),
    /* bc */ InstrCycle(ldy_absx_cyc1),
    /* bd */ InstrCycle(lda_absx_cyc1),
    /* be */ InstrCycle(ldx_absy_cyc1),
    /* bf */ InstrCycle(lda_abslx_cyc1),
    /* c0 */ InstrCycle(cpy_imm_cyc1),
    /* c1 */ InstrCycle(cmp::dxind_cyc1),
    /* c2 */ InstrCycle(todo_opcode!(0xc2)),
    /* c3 */ InstrCycle(cmp::sr_cyc1),
    /* c4 */ InstrCycle(cpy_d_cyc1),
    /* c5 */ InstrCycle(cmp::d_cyc1),
    /* c6 */ InstrCycle(todo_opcode!(0xc6)),
    /* c7 */ InstrCycle(cmp::dindl_cyc1),
    /* c8 */ InstrCycle(todo_opcode!(0xc8)),
    /* c9 */ InstrCycle(cmp::imm_cyc1),
    /* ca */ InstrCycle(todo_opcode!(0xca)),
    /* cb */ InstrCycle(todo_opcode!(0xcb)),
    /* cc */ InstrCycle(cpy_abs_cyc1),
    /* cd */ InstrCycle(cmp::abs_cyc1),
    /* ce */ InstrCycle(todo_opcode!(0xce)),
    /* cf */ InstrCycle(cmp::absl_cyc1),
    /* d0 */ InstrCycle(bne_cyc1),
    /* d1 */ InstrCycle(cmp::dindy_cyc1),
    /* d2 */ InstrCycle(cmp::dind_cyc1),
    /* d3 */ InstrCycle(cmp::sry_cyc1),
    /* d4 */ InstrCycle(todo_opcode!(0xd4)),
    /* d5 */ InstrCycle(cmp::dx_cyc1),
    /* d6 */ InstrCycle(todo_opcode!(0xd6)),
    /* d7 */ InstrCycle(cmp::dindly_cyc1),
    /* d8 */ InstrCycle(cld_cyc1),
    /* d9 */ InstrCycle(cmp::absy_cyc1),
    /* da */ InstrCycle(todo_opcode!(0xda)),
    /* db */ InstrCycle(todo_opcode!(0xdb)),
    /* dc */ InstrCycle(jml_cyc1),
    /* dd */ InstrCycle(cmp::absx_cyc1),
    /* de */ InstrCycle(todo_opcode!(0xde)),
    /* df */ InstrCycle(cmp::abslx_cyc1),
    /* e0 */ InstrCycle(cpx_imm_cyc1),
    /* e1 */ InstrCycle(sbc::dxind_cyc1),
    /* e2 */ InstrCycle(todo_opcode!(0xe2)),
    /* e3 */ InstrCycle(sbc::sr_cyc1),
    /* e4 */ InstrCycle(cpx_d_cyc1),
    /* e5 */ InstrCycle(sbc::d_cyc1),
    /* e6 */ InstrCycle(todo_opcode!(0xe6)),
    /* e7 */ InstrCycle(sbc::dindl_cyc1),
    /* e8 */ InstrCycle(inx_cyc1),
    /* e9 */ InstrCycle(sbc::imm_cyc1),
    /* ea */ InstrCycle(nop_cyc1),
    /* eb */ InstrCycle(todo_opcode!(0xeb)),
    /* ec */ InstrCycle(cpx_abs_cyc1),
    /* ed */ InstrCycle(sbc::abs_cyc1),
    /* ee */ InstrCycle(todo_opcode!(0xee)),
    /* ef */ InstrCycle(sbc::absl_cyc1),
    /* f0 */ InstrCycle(beq_cyc1),
    /* f1 */ InstrCycle(sbc::dindy_cyc1),
    /* f2 */ InstrCycle(sbc::dind_cyc1),
    /* f3 */ InstrCycle(sbc::sry_cyc1),
    /* f4 */ InstrCycle(todo_opcode!(0xf4)),
    /* f5 */ InstrCycle(sbc::dx_cyc1),
    /* f6 */ InstrCycle(todo_opcode!(0xf6)),
    /* f7 */ InstrCycle(sbc::dindly_cyc1),
    /* f8 */ InstrCycle(sed_cyc1),
    /* f9 */ InstrCycle(sbc::absy_cyc1),
    /* fa */ InstrCycle(todo_opcode!(0xfa)),
    /* fb */ InstrCycle(todo_opcode!(0xfb)),
    /* fc */ InstrCycle(jsr_abs_ind_xind_cyc1),
    /* fd */ InstrCycle(sbc::absx_cyc1),
    /* fe */ InstrCycle(todo_opcode!(0xfe)),
    /* ff */ InstrCycle(sbc::abslx_cyc1),
];
