use crate::cpu::{CPU, CycleResult};
use common::snes_address::SnesAddress;

use crate::instrs::{
    arithmetic::*, branches::*, flags::*, interrupts::*, jumps::*, loads::*, stack::*, stores::*,
    transfers::*, uncategorised::*,
};

pub struct InstrCycle(
    pub fn(&mut CPU) -> (CycleResult, InstrCycle),
    pub &'static str,
);

impl From<fn(&mut CPU) -> (CycleResult, InstrCycle)> for InstrCycle {
    fn from(value: fn(&mut CPU) -> (CycleResult, InstrCycle)) -> Self {
        InstrCycle(value, "unknown")
    }
}

pub(crate) fn opcode_fetch(cpu: &mut CPU) -> (CycleResult, InstrCycle) {
    cpu.addr_bus = SnesAddress {
        bank: cpu.registers.PB,
        addr: cpu.registers.PC,
    };
    (
        CycleResult::Read,
        InstrCycle(
            |next_cyc_cpu| {
                let opcode = next_cyc_cpu.data_bus as usize;
                let instr = &INSTR_CYC1[opcode];
                (instr.0)(next_cyc_cpu)
            },
            "opcode_fetch_dispatch",
        ),
    )
}

macro_rules! todo_opcode {
    ($oc:tt) => {
        |_| {
            todo!("opcode {:#2x} not yet implemented!", $oc);
        }
    };
}

const INSTR_CYC1: [InstrCycle; 256] = [
    /* 00 */ InstrCycle(brk_cyc1, "brk_cyc1"),
    /* 01 */ InstrCycle(ora::dxind_cyc1, "ora::dxind_cyc1"),
    /* 02 */ InstrCycle(cop_cyc1, "cop_cyc1"),
    /* 03 */ InstrCycle(ora::sr_cyc1, "ora::sr_cyc1"),
    /* 04 */ InstrCycle(tsb_d_cyc1, "tsb_d_cyc1"),
    /* 05 */ InstrCycle(ora::d_cyc1, "ora::d_cyc1"),
    /* 06 */ InstrCycle(asl_d_cyc1, "asl_d_cyc1"),
    /* 07 */ InstrCycle(ora::dindl_cyc1, "ora::dindl_cyc1"),
    /* 08 */ InstrCycle(php_cyc1, "php_cyc1"),
    /* 09 */ InstrCycle(ora::imm_cyc1, "ora::imm_cyc1"),
    /* 0a */ InstrCycle(asl_acc_cyc1, "asl_acc_cyc1"),
    /* 0b */ InstrCycle(phd_cyc1, "phd_cyc1"),
    /* 0c */ InstrCycle(tsb_abs_cyc1, "tsb_abs_cyc1"),
    /* 0d */ InstrCycle(ora::abs_cyc1, "ora::abs_cyc1"),
    /* 0e */ InstrCycle(asl_abs_cyc1, "asl_abs_cyc1"),
    /* 0f */ InstrCycle(ora::absl_cyc1, "ora::absl_cyc1"),
    /* 10 */ InstrCycle(bpl_cyc1, "bpl_cyc1"),
    /* 11 */ InstrCycle(ora::dindy_cyc1, "ora::dindy_cyc1"),
    /* 12 */ InstrCycle(ora::dind_cyc1, "ora::dind_cyc1"),
    /* 13 */ InstrCycle(ora::sry_cyc1, "ora::sry_cyc1"),
    /* 14 */ InstrCycle(trb_d_cyc1, "trb_d_cyc1"),
    /* 15 */ InstrCycle(ora::dx_cyc1, "ora::dx_cyc1"),
    /* 16 */ InstrCycle(asl_dx_cyc1, "asl_dx_cyc1"),
    /* 17 */ InstrCycle(ora::dindly_cyc1, "ora::dindly_cyc1"),
    /* 18 */ InstrCycle(clc_cyc1, "clc_cyc1"),
    /* 19 */ InstrCycle(ora::absy_cyc1, "ora::absy_cyc1"),
    /* 1a */ InstrCycle(inc_acc_cyc1, "inc_acc_cyc1"),
    /* 1b */ InstrCycle(tcs_cyc1, "tcs_cyc1"),
    /* 1c */ InstrCycle(trb_abs_cyc1, "trb_abs_cyc1"),
    /* 1d */ InstrCycle(ora::absx_cyc1, "ora::absx_cyc1"),
    /* 1e */ InstrCycle(asl_absx_cyc1, "asl_absx_cyc1"),
    /* 1f */ InstrCycle(ora::abslx_cyc1, "ora::abslx_cyc1"),
    /* 20 */ InstrCycle(jsr_abs_cyc1, "jsr_abs_cyc1"),
    /* 21 */ InstrCycle(and::dxind_cyc1, "and::dxind_cyc1"),
    /* 22 */ InstrCycle(jsl_cyc1, "jsl_cyc1"),
    /* 23 */ InstrCycle(and::sr_cyc1, "and::sr_cyc1"),
    /* 24 */ InstrCycle(bit_d_cyc1, "bit_d_cyc1"),
    /* 25 */ InstrCycle(and::d_cyc1, "and::d_cyc1"),
    /* 26 */ InstrCycle(rol_d_cyc1, "rol_d_cyc1"),
    /* 27 */ InstrCycle(and::dindl_cyc1, "and::dindl_cyc1"),
    /* 28 */ InstrCycle(plp_cyc1, "plp_cyc1"),
    /* 29 */ InstrCycle(and::imm_cyc1, "and::imm_cyc1"),
    /* 2a */ InstrCycle(rol_acc_cyc1, "rol_acc_cyc1"),
    /* 2b */ InstrCycle(pld_cyc1, "pld_cyc1"),
    /* 2c */ InstrCycle(bit_abs_cyc1, "bit_abs_cyc1"),
    /* 2d */ InstrCycle(and::abs_cyc1, "and::abs_cyc1"),
    /* 2e */ InstrCycle(rol_abs_cyc1, "rol_abs_cyc1"),
    /* 2f */ InstrCycle(and::absl_cyc1, "and::absl_cyc1"),
    /* 30 */ InstrCycle(bmi_cyc1, "bmi_cyc1"),
    /* 31 */ InstrCycle(and::dindy_cyc1, "and::dindy_cyc1"),
    /* 32 */ InstrCycle(and::dind_cyc1, "and::dind_cyc1"),
    /* 33 */ InstrCycle(and::sry_cyc1, "and::sry_cyc1"),
    /* 34 */ InstrCycle(bit_dx_cyc1, "bit_dx_cyc1"),
    /* 35 */ InstrCycle(and::dx_cyc1, "and::dx_cyc1"),
    /* 36 */ InstrCycle(rol_dx_cyc1, "rol_dx_cyc1"),
    /* 37 */ InstrCycle(and::dindly_cyc1, "and::dindly_cyc1"),
    /* 38 */ InstrCycle(sec_cyc1, "sec_cyc1"),
    /* 39 */ InstrCycle(and::absy_cyc1, "and::absy_cyc1"),
    /* 3a */ InstrCycle(dec_acc_cyc1, "dec_acc_cyc1"),
    /* 3b */ InstrCycle(tsc_cyc1, "tsc_cyc1"),
    /* 3c */ InstrCycle(bit_absx_cyc1, "bit_absx_cyc1"),
    /* 3d */ InstrCycle(and::absx_cyc1, "and::absx_cyc1"),
    /* 3e */ InstrCycle(rol_absx_cyc1, "rol_absx_cyc1"),
    /* 3f */ InstrCycle(and::abslx_cyc1, "and::abslx_cyc1"),
    /* 40 */ InstrCycle(todo_opcode!(0x40), "todo(0x40)"),
    /* 41 */ InstrCycle(eor::dxind_cyc1, "eor::dxind_cyc1"),
    /* 42 */ InstrCycle(wdm_cyc1, "wdm_cyc1"),
    /* 43 */ InstrCycle(eor::sr_cyc1, "eor::sr_cyc1"),
    /* 44 */ InstrCycle(mvp_cyc1, "mvp_cyc1"),
    /* 45 */ InstrCycle(eor::d_cyc1, "eor::d_cyc1"),
    /* 46 */ InstrCycle(lsr_d_cyc1, "lsr_d_cyc1"),
    /* 47 */ InstrCycle(eor::dindl_cyc1, "eor::dindl_cyc1"),
    /* 48 */ InstrCycle(pha_cyc1, "pha_cyc1"),
    /* 49 */ InstrCycle(eor::imm_cyc1, "eor::imm_cyc1"),
    /* 4a */ InstrCycle(lsr_acc_cyc1, "lsr_acc_cyc1"),
    /* 4b */ InstrCycle(phk_cyc1, "phk_cyc1"),
    /* 4c */ InstrCycle(jmp_abs_cyc1, "jmp_abs_cyc1"),
    /* 4d */ InstrCycle(eor::abs_cyc1, "eor::abs_cyc1"),
    /* 4e */ InstrCycle(lsr_d_cyc1, "lsr_d_cyc1"),
    /* 4f */ InstrCycle(eor::absl_cyc1, "eor::absl_cyc1"),
    /* 50 */ InstrCycle(bvc_cyc1, "bvc_cyc1"),
    /* 51 */ InstrCycle(eor::dindy_cyc1, "eor::dindy_cyc1"),
    /* 52 */ InstrCycle(eor::dind_cyc1, "eor::dind_cyc1"),
    /* 53 */ InstrCycle(eor::sry_cyc1, "eor::sry_cyc1"),
    /* 54 */ InstrCycle(mvn_cyc1, "mvn_cyc1"),
    /* 55 */ InstrCycle(eor::dx_cyc1, "eor::dx_cyc1"),
    /* 56 */ InstrCycle(lsr_dx_cyc1, "lsr_dx_cyc1"),
    /* 57 */ InstrCycle(eor::dindly_cyc1, "eor::dindly_cyc1"),
    /* 58 */ InstrCycle(cli_cyc1, "cli_cyc1"),
    /* 59 */ InstrCycle(eor::absy_cyc1, "eor::absy_cyc1"),
    /* 5a */ InstrCycle(phy_cyc1, "phy_cyc1"),
    /* 5b */ InstrCycle(tcd_cyc1, "tcd_cyc1"),
    /* 5c */ InstrCycle(jmp_absl_cyc1, "jmp_absl_cyc1"),
    /* 5d */ InstrCycle(eor::absx_cyc1, "eor::absx_cyc1"),
    /* 5e */ InstrCycle(lsr_absx_cyc1, "lsr_absx_cyc1"),
    /* 5f */ InstrCycle(eor::abslx_cyc1, "eor::abslx_cyc1"),
    /* 60 */ InstrCycle(rts_cyc1, "rts_cyc1"),
    /* 61 */ InstrCycle(adc::dxind_cyc1, "adc::dxind_cyc1"),
    /* 62 */ InstrCycle(per_cyc1, "per_cyc1"),
    /* 63 */ InstrCycle(adc::sr_cyc1, "adc::sr_cyc1"),
    /* 64 */ InstrCycle(stz_d_cyc1, "stz_d_cyc1"),
    /* 65 */ InstrCycle(adc::d_cyc1, "adc::d_cyc1"),
    /* 66 */ InstrCycle(ror_d_cyc1, "ror_d_cyc1"),
    /* 67 */ InstrCycle(adc::dindl_cyc1, "adc::dindl_cyc1"),
    /* 68 */ InstrCycle(pla_cyc1, "pla_cyc1"),
    /* 69 */ InstrCycle(adc::imm_cyc1, "adc::imm_cyc1"),
    /* 6a */ InstrCycle(ror_acc_cyc1, "ror_acc_cyc1"),
    /* 6b */ InstrCycle(rtl_cyc1, "rtl_cyc1"),
    /* 6c */ InstrCycle(jmp_abs_ind_cyc1, "jmp_abs_ind_cyc1"),
    /* 6d */ InstrCycle(adc::abs_cyc1, "adc::abs_cyc1"),
    /* 6e */ InstrCycle(ror_abs_cyc1, "ror_abs_cyc1"),
    /* 6f */ InstrCycle(adc::absl_cyc1, "adc::absl_cyc1"),
    /* 70 */ InstrCycle(bvs_cyc1, "bvs_cyc1"),
    /* 71 */ InstrCycle(adc::dindy_cyc1, "adc::dindy_cyc1"),
    /* 72 */ InstrCycle(adc::dind_cyc1, "adc::dind_cyc1"),
    /* 73 */ InstrCycle(adc::sry_cyc1, "adc::sry_cyc1"),
    /* 74 */ InstrCycle(stz_dx_cyc1, "stz_dx_cyc1"),
    /* 75 */ InstrCycle(adc::dx_cyc1, "adc::dx_cyc1"),
    /* 76 */ InstrCycle(ror_dx_cyc1, "ror_dx_cyc1"),
    /* 77 */ InstrCycle(adc::dindly_cyc1, "adc::dindly_cyc1"),
    /* 78 */ InstrCycle(sei_cyc1, "sei_cyc1"),
    /* 79 */ InstrCycle(adc::absy_cyc1, "adc::absy_cyc1"),
    /* 7a */ InstrCycle(ply_cyc1, "ply_cyc1"),
    /* 7b */ InstrCycle(tdc_cyc1, "tdc_cyc1"),
    /* 7c */ InstrCycle(jmp_abs_ind_indx_cyc1, "jmp_abs_ind_indx_cyc1"),
    /* 7d */ InstrCycle(adc::absx_cyc1, "adc::absx_cyc1"),
    /* 7e */ InstrCycle(ror_absx_cyc1, "ror_absx_cyc1"),
    /* 7f */ InstrCycle(adc::abslx_cyc1, "adc::abslx_cyc1"),
    /* 80 */ InstrCycle(bra_cyc1, "bra_cyc1"),
    /* 81 */ InstrCycle(sta_dxind_cyc1, "sta_dxind_cyc1"),
    /* 82 */ InstrCycle(brl_cyc1, "brl_cyc1"),
    /* 83 */ InstrCycle(sta_sr_cyc1, "sta_sr_cyc1"),
    /* 84 */ InstrCycle(sty_d_cyc1, "sty_d_cyc1"),
    /* 85 */ InstrCycle(sta_d_cyc1, "sta_d_cyc1"),
    /* 86 */ InstrCycle(stx_d_cyc1, "stx_d_cyc1"),
    /* 87 */ InstrCycle(sta_dindl_cyc1, "sta_dindl_cyc1"),
    /* 88 */ InstrCycle(dey_cyc1, "dey_cyc1"),
    /* 89 */ InstrCycle(bit_imm_cyc1, "bit_imm_cyc1"),
    /* 8a */ InstrCycle(txa_cyc1, "txa_cyc1"),
    /* 8b */ InstrCycle(phb_cyc1, "phb_cyc1"),
    /* 8c */ InstrCycle(sty_abs_cyc1, "sty_abs_cyc1"),
    /* 8d */ InstrCycle(sta_abs_cyc1, "sta_abs_cyc1"),
    /* 8e */ InstrCycle(stx_abs_cyc1, "stx_abs_cyc1"),
    /* 8f */ InstrCycle(sta_absl_cyc1, "sta_absl_cyc1"),
    /* 90 */ InstrCycle(bcc_cyc1, "bcc_cyc1"),
    /* 91 */ InstrCycle(sta_dindy_cyc1, "sta_dindy_cyc1"),
    /* 92 */ InstrCycle(sta_dind_cyc1, "sta_dind_cyc1"),
    /* 93 */ InstrCycle(sta_sry_cyc1, "sta_sry_cyc1"),
    /* 94 */ InstrCycle(sty_dx_cyc1, "sty_dx_cyc1"),
    /* 95 */ InstrCycle(sta_dx_cyc1, "sta_dx_cyc1"),
    /* 96 */ InstrCycle(stx_dy_cyc1, "stx_dy_cyc1"),
    /* 97 */ InstrCycle(sta_dindly_cyc1, "sta_dindly_cyc1"),
    /* 98 */ InstrCycle(tya_cyc1, "tya_cyc1"),
    /* 99 */ InstrCycle(sta_absy_cyc1, "sta_absy_cyc1"),
    /* 9a */ InstrCycle(txs_cyc1, "txs_cyc1"),
    /* 9b */ InstrCycle(txy_cyc1, "txy_cyc1"),
    /* 9c */ InstrCycle(stz_abs_cyc1, "stz_abs_cyc1"),
    /* 9d */ InstrCycle(sta_absx_cyc1, "sta_absx_cyc1"),
    /* 9e */ InstrCycle(stz_absx_cyc1, "stz_absx_cyc1"),
    /* 9f */ InstrCycle(sta_abslx_cyc1, "sta_abslx_cyc1"),
    /* a0 */ InstrCycle(ldy_imm_cyc1, "ldy_imm_cyc1"),
    /* a1 */ InstrCycle(lda_dxind_cyc1, "lda_dxind_cyc1"),
    /* a2 */ InstrCycle(ldx_imm_cyc1, "ldx_imm_cyc1"),
    /* a3 */ InstrCycle(lda_sr_cyc1, "lda_sr_cyc1"),
    /* a4 */ InstrCycle(ldy_d_cyc1, "ldy_d_cyc1"),
    /* a5 */ InstrCycle(lda_d_cyc1, "lda_d_cyc1"),
    /* a6 */ InstrCycle(ldx_d_cyc1, "ldx_d_cyc1"),
    /* a7 */ InstrCycle(lda_dindl_cyc1, "lda_dindl_cyc1"),
    /* a8 */ InstrCycle(tay_cyc1, "tay_cyc1"),
    /* a9 */ InstrCycle(lda_imm_cyc1, "lda_imm_cyc1"),
    /* aa */ InstrCycle(tax_cyc1, "tax_cyc1"),
    /* ab */ InstrCycle(plb_cyc1, "plb_cyc1"),
    /* ac */ InstrCycle(ldy_abs_cyc1, "ldy_abs_cyc1"),
    /* ad */ InstrCycle(lda_abs_cyc1, "lda_abs_cyc1"),
    /* ae */ InstrCycle(ldx_abs_cyc1, "ldx_abs_cyc1"),
    /* af */ InstrCycle(lda_absl_cyc1, "lda_absl_cyc1"),
    /* b0 */ InstrCycle(bcs_cyc1, "bcs_cyc1"),
    /* b1 */ InstrCycle(lda_dindy_cyc1, "lda_dindy_cyc1"),
    /* b2 */ InstrCycle(lda_dind_cyc1, "lda_dind_cyc1"),
    /* b3 */ InstrCycle(lda_sry_cyc1, "lda_sry_cyc1"),
    /* b4 */ InstrCycle(ldy_dx_cyc1, "ldy_dx_cyc1"),
    /* b5 */ InstrCycle(lda_dx_cyc1, "lda_dx_cyc1"),
    /* b6 */ InstrCycle(ldx_dy_cyc1, "ldx_dy_cyc1"),
    /* b7 */ InstrCycle(lda_dindly_cyc1, "lda_dindly_cyc1"),
    /* b8 */ InstrCycle(clv_cyc1, "clv_cyc1"),
    /* b9 */ InstrCycle(lda_absy_cyc1, "lda_absy_cyc1"),
    /* ba */ InstrCycle(tsx_cyc1, "tsx_cyc1"),
    /* bb */ InstrCycle(tyx_cyc1, "tyx_cyc1"),
    /* bc */ InstrCycle(ldy_absx_cyc1, "ldy_absx_cyc1"),
    /* bd */ InstrCycle(lda_absx_cyc1, "lda_absx_cyc1"),
    /* be */ InstrCycle(ldx_absy_cyc1, "ldx_absy_cyc1"),
    /* bf */ InstrCycle(lda_abslx_cyc1, "lda_abslx_cyc1"),
    /* c0 */ InstrCycle(cpy_imm_cyc1, "cpy_imm_cyc1"),
    /* c1 */ InstrCycle(cmp::dxind_cyc1, "cmp::dxind_cyc1"),
    /* c2 */ InstrCycle(rep_cyc1, "rep_cyc1"),
    /* c3 */ InstrCycle(cmp::sr_cyc1, "cmp::sr_cyc1"),
    /* c4 */ InstrCycle(cpy_d_cyc1, "cpy_d_cyc1"),
    /* c5 */ InstrCycle(cmp::d_cyc1, "cmp::d_cyc1"),
    /* c6 */ InstrCycle(dec_d_cyc1, "dec_d_cyc1"),
    /* c7 */ InstrCycle(cmp::dindl_cyc1, "cmp::dindl_cyc1"),
    /* c8 */ InstrCycle(iny_cyc1, "iny_cyc1"),
    /* c9 */ InstrCycle(cmp::imm_cyc1, "cmp::imm_cyc1"),
    /* ca */ InstrCycle(dex_cyc1, "dex_cyc1"),
    /* cb */ InstrCycle(todo_opcode!(0xcb), "todo(0xcb)"),
    /* cc */ InstrCycle(cpy_abs_cyc1, "cpy_abs_cyc1"),
    /* cd */ InstrCycle(cmp::abs_cyc1, "cmp::abs_cyc1"),
    /* ce */ InstrCycle(dec_abs_cyc1, "dec_abs_cyc1"),
    /* cf */ InstrCycle(cmp::absl_cyc1, "cmp::absl_cyc1"),
    /* d0 */ InstrCycle(bne_cyc1, "bne_cyc1"),
    /* d1 */ InstrCycle(cmp::dindy_cyc1, "cmp::dindy_cyc1"),
    /* d2 */ InstrCycle(cmp::dind_cyc1, "cmp::dind_cyc1"),
    /* d3 */ InstrCycle(cmp::sry_cyc1, "cmp::sry_cyc1"),
    /* d4 */ InstrCycle(pei_cyc1, "pei_cyc1"),
    /* d5 */ InstrCycle(cmp::dx_cyc1, "cmp::dx_cyc1"),
    /* d6 */ InstrCycle(dec_dx_cyc1, "dec_dx_cyc1"),
    /* d7 */ InstrCycle(cmp::dindly_cyc1, "cmp::dindly_cyc1"),
    /* d8 */ InstrCycle(cld_cyc1, "cld_cyc1"),
    /* d9 */ InstrCycle(cmp::absy_cyc1, "cmp::absy_cyc1"),
    /* da */ InstrCycle(phx_cyc1, "phx_cyc1"),
    /* db */ InstrCycle(stp_cyc1, "stp_cyc1"),
    /* dc */ InstrCycle(jml_cyc1, "jml_cyc1"),
    /* dd */ InstrCycle(cmp::absx_cyc1, "cmp::absx_cyc1"),
    /* de */ InstrCycle(dec_absx_cyc1, "dec_absx_cyc1"),
    /* df */ InstrCycle(cmp::abslx_cyc1, "cmp::abslx_cyc1"),
    /* e0 */ InstrCycle(cpx_imm_cyc1, "cpx_imm_cyc1"),
    /* e1 */ InstrCycle(sbc::dxind_cyc1, "sbc::dxind_cyc1"),
    /* e2 */ InstrCycle(sep_cyc1, "sep_cyc1"),
    /* e3 */ InstrCycle(sbc::sr_cyc1, "sbc::sr_cyc1"),
    /* e4 */ InstrCycle(cpx_d_cyc1, "cpx_d_cyc1"),
    /* e5 */ InstrCycle(sbc::d_cyc1, "sbc::d_cyc1"),
    /* e6 */ InstrCycle(inc_d_cyc1, "inc_d_cyc1"),
    /* e7 */ InstrCycle(sbc::dindl_cyc1, "sbc::dindl_cyc1"),
    /* e8 */ InstrCycle(inx_cyc1, "inx_cyc1"),
    /* e9 */ InstrCycle(sbc::imm_cyc1, "sbc::imm_cyc1"),
    /* ea */ InstrCycle(nop_cyc1, "nop_cyc1"),
    /* eb */ InstrCycle(xba_cyc1, "xba_cyc1"),
    /* ec */ InstrCycle(cpx_abs_cyc1, "cpx_abs_cyc1"),
    /* ed */ InstrCycle(sbc::abs_cyc1, "sbc::abs_cyc1"),
    /* ee */ InstrCycle(inc_abs_cyc1, "inc_abs_cyc1"),
    /* ef */ InstrCycle(sbc::absl_cyc1, "sbc::absl_cyc1"),
    /* f0 */ InstrCycle(beq_cyc1, "beq_cyc1"),
    /* f1 */ InstrCycle(sbc::dindy_cyc1, "sbc::dindy_cyc1"),
    /* f2 */ InstrCycle(sbc::dind_cyc1, "sbc::dind_cyc1"),
    /* f3 */ InstrCycle(sbc::sry_cyc1, "sbc::sry_cyc1"),
    /* f4 */ InstrCycle(pea_cyc1, "pea_cyc1"),
    /* f5 */ InstrCycle(sbc::dx_cyc1, "sbc::dx_cyc1"),
    /* f6 */ InstrCycle(inc_dx_cyc1, "inc_dx_cyc1"),
    /* f7 */ InstrCycle(sbc::dindly_cyc1, "sbc::dindly_cyc1"),
    /* f8 */ InstrCycle(sed_cyc1, "sed_cyc1"),
    /* f9 */ InstrCycle(sbc::absy_cyc1, "sbc::absy_cyc1"),
    /* fa */ InstrCycle(plx_cyc1, "plx_cyc1"),
    /* fb */ InstrCycle(xce_cyc1, "xce_cyc1"),
    /* fc */ InstrCycle(jsr_abs_ind_xind_cyc1, "jsr_abs_ind_xind_cyc1"),
    /* fd */ InstrCycle(sbc::absx_cyc1, "sbc::absx_cyc1"),
    /* fe */ InstrCycle(inc_absx_cyc1, "inc_absx_cyc1"),
    /* ff */ InstrCycle(sbc::abslx_cyc1, "sbc::abslx_cyc1"),
];
