use crate::cpu::{CPU, CycleResult};
use common::snes_address::SnesAddress;

use crate::instrs::{
    flags::*,
    jumps::*,
    loads::*,
    stores::*,
    uncategorised::*,
};

pub(crate) struct InstrCycle(pub fn(&mut CPU) -> (CycleResult, InstrCycle));

impl From<fn(&mut CPU) -> (CycleResult, InstrCycle)> for InstrCycle {
    fn from(value: fn(&mut CPU) -> (CycleResult, InstrCycle)) -> Self {
        InstrCycle(value)
    }
}

pub(crate) fn opcode_fetch(cpu: &mut CPU) -> (CycleResult, InstrCycle) {
    cpu.addr_bus = SnesAddress {
        bank: cpu.registers.PB,
        addr: cpu.registers.PC,
    };

    (
        CycleResult::Read,
        InstrCycle(|next_cyc_cpu| (INSTR_CYC1[next_cyc_cpu.data_bus as usize].0)(next_cyc_cpu)),
    )
}

macro_rules! todo_opcode {
    ($oc:tt) => {
        |_| {
            todo!("opcode {:#2x} not yet implemented!", $oc);
        }
    }
}

const INSTR_CYC1: [InstrCycle; 256] = [
    /* 00 */ InstrCycle(todo_opcode!(0x00)),
    /* 01 */ InstrCycle(todo_opcode!(0x01)),
    /* 02 */ InstrCycle(todo_opcode!(0x02)),
    /* 03 */ InstrCycle(todo_opcode!(0x03)),
    /* 04 */ InstrCycle(todo_opcode!(0x04)),
    /* 05 */ InstrCycle(todo_opcode!(0x05)),
    /* 06 */ InstrCycle(todo_opcode!(0x06)),
    /* 07 */ InstrCycle(todo_opcode!(0x07)),
    /* 08 */ InstrCycle(todo_opcode!(0x08)),
    /* 09 */ InstrCycle(todo_opcode!(0x09)),
    /* 0a */ InstrCycle(todo_opcode!(0x0a)),
    /* 0b */ InstrCycle(todo_opcode!(0x0b)),
    /* 0c */ InstrCycle(todo_opcode!(0x0c)),
    /* 0d */ InstrCycle(todo_opcode!(0x0d)),
    /* 0e */ InstrCycle(todo_opcode!(0x0e)),
    /* 0f */ InstrCycle(todo_opcode!(0x0f)),
    /* 10 */ InstrCycle(todo_opcode!(0x10)),
    /* 11 */ InstrCycle(todo_opcode!(0x11)),
    /* 12 */ InstrCycle(todo_opcode!(0x12)),
    /* 13 */ InstrCycle(todo_opcode!(0x13)),
    /* 14 */ InstrCycle(todo_opcode!(0x14)),
    /* 15 */ InstrCycle(todo_opcode!(0x15)),
    /* 16 */ InstrCycle(todo_opcode!(0x16)),
    /* 17 */ InstrCycle(todo_opcode!(0x17)),
    /* 18 */ InstrCycle(clc_cyc1),
    /* 19 */ InstrCycle(todo_opcode!(0x19)),
    /* 1a */ InstrCycle(todo_opcode!(0x1a)),
    /* 1b */ InstrCycle(todo_opcode!(0x1b)),
    /* 1c */ InstrCycle(todo_opcode!(0x1c)),
    /* 1d */ InstrCycle(todo_opcode!(0x1d)),
    /* 1e */ InstrCycle(todo_opcode!(0x1e)),
    /* 1f */ InstrCycle(todo_opcode!(0x1f)),
    /* 20 */ InstrCycle(jsr_abs_cyc1),
    /* 21 */ InstrCycle(todo_opcode!(0x21)),
    /* 22 */ InstrCycle(jsl_cyc1),
    /* 23 */ InstrCycle(todo_opcode!(0x23)),
    /* 24 */ InstrCycle(todo_opcode!(0x24)),
    /* 25 */ InstrCycle(todo_opcode!(0x25)),
    /* 26 */ InstrCycle(todo_opcode!(0x26)),
    /* 27 */ InstrCycle(todo_opcode!(0x27)),
    /* 28 */ InstrCycle(todo_opcode!(0x28)),
    /* 29 */ InstrCycle(todo_opcode!(0x29)),
    /* 2a */ InstrCycle(todo_opcode!(0x2a)),
    /* 2b */ InstrCycle(todo_opcode!(0x2b)),
    /* 2c */ InstrCycle(todo_opcode!(0x2c)),
    /* 2d */ InstrCycle(todo_opcode!(0x2d)),
    /* 2e */ InstrCycle(todo_opcode!(0x2e)),
    /* 2f */ InstrCycle(todo_opcode!(0x2f)),
    /* 30 */ InstrCycle(todo_opcode!(0x30)),
    /* 31 */ InstrCycle(todo_opcode!(0x31)),
    /* 32 */ InstrCycle(todo_opcode!(0x32)),
    /* 33 */ InstrCycle(todo_opcode!(0x33)),
    /* 34 */ InstrCycle(todo_opcode!(0x34)),
    /* 35 */ InstrCycle(todo_opcode!(0x35)),
    /* 36 */ InstrCycle(todo_opcode!(0x36)),
    /* 37 */ InstrCycle(todo_opcode!(0x37)),
    /* 38 */ InstrCycle(sec_cyc1),
    /* 39 */ InstrCycle(todo_opcode!(0x39)),
    /* 3a */ InstrCycle(todo_opcode!(0x3a)),
    /* 3b */ InstrCycle(todo_opcode!(0x3b)),
    /* 3c */ InstrCycle(todo_opcode!(0x3c)),
    /* 3d */ InstrCycle(todo_opcode!(0x3d)),
    /* 3e */ InstrCycle(todo_opcode!(0x3e)),
    /* 3f */ InstrCycle(todo_opcode!(0x3f)),
    /* 40 */ InstrCycle(todo_opcode!(0x40)),
    /* 41 */ InstrCycle(todo_opcode!(0x41)),
    /* 42 */ InstrCycle(todo_opcode!(0x42)),
    /* 43 */ InstrCycle(todo_opcode!(0x43)),
    /* 44 */ InstrCycle(todo_opcode!(0x44)),
    /* 45 */ InstrCycle(todo_opcode!(0x45)),
    /* 46 */ InstrCycle(todo_opcode!(0x46)),
    /* 47 */ InstrCycle(todo_opcode!(0x47)),
    /* 48 */ InstrCycle(todo_opcode!(0x48)),
    /* 49 */ InstrCycle(todo_opcode!(0x49)),
    /* 4a */ InstrCycle(todo_opcode!(0x4a)),
    /* 4b */ InstrCycle(todo_opcode!(0x4b)),
    /* 4c */ InstrCycle(jmp_abs_cyc1),
    /* 4d */ InstrCycle(todo_opcode!(0x4d)),
    /* 4e */ InstrCycle(todo_opcode!(0x4e)),
    /* 4f */ InstrCycle(todo_opcode!(0x4f)),
    /* 50 */ InstrCycle(todo_opcode!(0x50)),
    /* 51 */ InstrCycle(todo_opcode!(0x51)),
    /* 52 */ InstrCycle(todo_opcode!(0x52)),
    /* 53 */ InstrCycle(todo_opcode!(0x53)),
    /* 54 */ InstrCycle(todo_opcode!(0x54)),
    /* 55 */ InstrCycle(todo_opcode!(0x55)),
    /* 56 */ InstrCycle(todo_opcode!(0x56)),
    /* 57 */ InstrCycle(todo_opcode!(0x57)),
    /* 58 */ InstrCycle(cli_cyc1),
    /* 59 */ InstrCycle(todo_opcode!(0x59)),
    /* 5a */ InstrCycle(todo_opcode!(0x5a)),
    /* 5b */ InstrCycle(todo_opcode!(0x5b)),
    /* 5c */ InstrCycle(jmp_absl_cyc1),
    /* 5d */ InstrCycle(todo_opcode!(0x5d)),
    /* 5e */ InstrCycle(todo_opcode!(0x5e)),
    /* 5f */ InstrCycle(todo_opcode!(0x5f)),
    /* 60 */ InstrCycle(rts_cyc1),
    /* 61 */ InstrCycle(todo_opcode!(0x61)),
    /* 62 */ InstrCycle(todo_opcode!(0x62)),
    /* 63 */ InstrCycle(todo_opcode!(0x63)),
    /* 64 */ InstrCycle(stz_d_cyc1),
    /* 65 */ InstrCycle(todo_opcode!(0x65)),
    /* 66 */ InstrCycle(todo_opcode!(0x66)),
    /* 67 */ InstrCycle(todo_opcode!(0x67)),
    /* 68 */ InstrCycle(todo_opcode!(0x68)),
    /* 69 */ InstrCycle(todo_opcode!(0x69)),
    /* 6a */ InstrCycle(todo_opcode!(0x6a)),
    /* 6b */ InstrCycle(rtl_cyc1),
    /* 6c */ InstrCycle(jmp_abs_ind_cyc1),
    /* 6d */ InstrCycle(todo_opcode!(0x6d)),
    /* 6e */ InstrCycle(todo_opcode!(0x6e)),
    /* 6f */ InstrCycle(todo_opcode!(0x6f)),
    /* 70 */ InstrCycle(todo_opcode!(0x70)),
    /* 71 */ InstrCycle(todo_opcode!(0x71)),
    /* 72 */ InstrCycle(todo_opcode!(0x72)),
    /* 73 */ InstrCycle(todo_opcode!(0x73)),
    /* 74 */ InstrCycle(stz_dx_cyc1),
    /* 75 */ InstrCycle(todo_opcode!(0x75)),
    /* 76 */ InstrCycle(todo_opcode!(0x76)),
    /* 77 */ InstrCycle(todo_opcode!(0x77)),
    /* 78 */ InstrCycle(sei_cyc1),
    /* 79 */ InstrCycle(todo_opcode!(0x79)),
    /* 7a */ InstrCycle(todo_opcode!(0x7a)),
    /* 7b */ InstrCycle(todo_opcode!(0x7b)),
    /* 7c */ InstrCycle(jmp_abs_ind_indx_cyc1),
    /* 7d */ InstrCycle(todo_opcode!(0x7d)),
    /* 7e */ InstrCycle(todo_opcode!(0x7e)),
    /* 7f */ InstrCycle(todo_opcode!(0x7f)),
    /* 80 */ InstrCycle(todo_opcode!(0x80)),
    /* 81 */ InstrCycle(sta_dxind_cyc1),
    /* 82 */ InstrCycle(todo_opcode!(0x82)),
    /* 83 */ InstrCycle(sta_sr_cyc1),
    /* 84 */ InstrCycle(sty_d_cyc1),
    /* 85 */ InstrCycle(sta_d_cyc1),
    /* 86 */ InstrCycle(stx_d_cyc1),
    /* 87 */ InstrCycle(sta_dindl_cyc1),
    /* 88 */ InstrCycle(todo_opcode!(0x88)),
    /* 89 */ InstrCycle(todo_opcode!(0x89)),
    /* 8a */ InstrCycle(todo_opcode!(0x8a)),
    /* 8b */ InstrCycle(todo_opcode!(0x8b)),
    /* 8c */ InstrCycle(sty_abs_cyc1),
    /* 8d */ InstrCycle(sta_abs_cyc1),
    /* 8e */ InstrCycle(stx_abs_cyc1),
    /* 8f */ InstrCycle(sta_absl_cyc1),
    /* 90 */ InstrCycle(todo_opcode!(0x90)),
    /* 91 */ InstrCycle(sta_dindy_cyc1),
    /* 92 */ InstrCycle(sta_dind_cyc1),
    /* 93 */ InstrCycle(sta_sry_cyc1),
    /* 94 */ InstrCycle(sty_dx_cyc1),
    /* 95 */ InstrCycle(sta_dx_cyc1),
    /* 96 */ InstrCycle(stx_dy_cyc1),
    /* 97 */ InstrCycle(sta_dindly_cyc1),
    /* 98 */ InstrCycle(todo_opcode!(0x98)),
    /* 99 */ InstrCycle(sta_absy_cyc1),
    /* 9a */ InstrCycle(todo_opcode!(0x9a)),
    /* 9b */ InstrCycle(todo_opcode!(0x9b)),
    /* 9c */ InstrCycle(stz_abs_cyc1),
    /* 9d */ InstrCycle(sta_absx_cyc1),
    /* 9e */ InstrCycle(stz_absx_cyc1),
    /* 9f */ InstrCycle(sta_abslx_cyc1),
    /* a0 */ InstrCycle(ldy_imm_cyc1),
    /* a1 */ InstrCycle(lda_dxind_cyc1),
    /* a2 */ InstrCycle(ldx_imm_cyc1),
    /* a3 */ InstrCycle(lda_sr_cyc1),
    /* a4 */ InstrCycle(ldy_d_cyc1),
    /* a5 */ InstrCycle(lda_d_cyc1),
    /* a6 */ InstrCycle(ldx_d_cyc1),
    /* a7 */ InstrCycle(lda_dindl_cyc1),
    /* a8 */ InstrCycle(todo_opcode!(0xa8)),
    /* a9 */ InstrCycle(lda_imm_cyc1),
    /* aa */ InstrCycle(todo_opcode!(0xaa)),
    /* ab */ InstrCycle(todo_opcode!(0xab)),
    /* ac */ InstrCycle(ldy_abs_cyc1),
    /* ad */ InstrCycle(lda_abs_cyc1),
    /* ae */ InstrCycle(ldx_abs_cyc1),
    /* af */ InstrCycle(lda_absl_cyc1),
    /* b0 */ InstrCycle(todo_opcode!(0xb0)),
    /* b1 */ InstrCycle(lda_dindy_cyc1),
    /* b2 */ InstrCycle(lda_dind_cyc1),
    /* b3 */ InstrCycle(lda_sry_cyc1),
    /* b4 */ InstrCycle(ldy_dx_cyc1),
    /* b5 */ InstrCycle(lda_dx_cyc1),
    /* b6 */ InstrCycle(ldx_dy_cyc1),
    /* b7 */ InstrCycle(lda_dindly_cyc1),
    /* b8 */ InstrCycle(clv_cyc1),
    /* b9 */ InstrCycle(lda_absy_cyc1),
    /* ba */ InstrCycle(todo_opcode!(0xba)),
    /* bb */ InstrCycle(todo_opcode!(0xbb)),
    /* bc */ InstrCycle(ldy_absx_cyc1),
    /* bd */ InstrCycle(lda_absx_cyc1),
    /* be */ InstrCycle(ldx_absy_cyc1),
    /* bf */ InstrCycle(lda_abslx_cyc1),
    /* c0 */ InstrCycle(todo_opcode!(0xc0)),
    /* c1 */ InstrCycle(todo_opcode!(0xc1)),
    /* c2 */ InstrCycle(todo_opcode!(0xc2)),
    /* c3 */ InstrCycle(todo_opcode!(0xc3)),
    /* c4 */ InstrCycle(todo_opcode!(0xc4)),
    /* c5 */ InstrCycle(todo_opcode!(0xc5)),
    /* c6 */ InstrCycle(todo_opcode!(0xc6)),
    /* c7 */ InstrCycle(todo_opcode!(0xc7)),
    /* c8 */ InstrCycle(todo_opcode!(0xc8)),
    /* c9 */ InstrCycle(todo_opcode!(0xc9)),
    /* ca */ InstrCycle(todo_opcode!(0xca)),
    /* cb */ InstrCycle(todo_opcode!(0xcb)),
    /* cc */ InstrCycle(todo_opcode!(0xcc)),
    /* cd */ InstrCycle(todo_opcode!(0xcd)),
    /* ce */ InstrCycle(todo_opcode!(0xce)),
    /* cf */ InstrCycle(todo_opcode!(0xcf)),
    /* d0 */ InstrCycle(todo_opcode!(0xd0)),
    /* d1 */ InstrCycle(todo_opcode!(0xd1)),
    /* d2 */ InstrCycle(todo_opcode!(0xd2)),
    /* d3 */ InstrCycle(todo_opcode!(0xd3)),
    /* d4 */ InstrCycle(todo_opcode!(0xd4)),
    /* d5 */ InstrCycle(todo_opcode!(0xd5)),
    /* d6 */ InstrCycle(todo_opcode!(0xd6)),
    /* d7 */ InstrCycle(todo_opcode!(0xd7)),
    /* d8 */ InstrCycle(cld_cyc1),
    /* d9 */ InstrCycle(todo_opcode!(0xd9)),
    /* da */ InstrCycle(todo_opcode!(0xda)),
    /* db */ InstrCycle(todo_opcode!(0xdb)),
    /* dc */ InstrCycle(jml_cyc1),
    /* dd */ InstrCycle(todo_opcode!(0xdd)),
    /* de */ InstrCycle(todo_opcode!(0xde)),
    /* df */ InstrCycle(todo_opcode!(0xdf)),
    /* e0 */ InstrCycle(todo_opcode!(0xe0)),
    /* e1 */ InstrCycle(todo_opcode!(0xe1)),
    /* e2 */ InstrCycle(todo_opcode!(0xe2)),
    /* e3 */ InstrCycle(todo_opcode!(0xe3)),
    /* e4 */ InstrCycle(todo_opcode!(0xe4)),
    /* e5 */ InstrCycle(todo_opcode!(0xe5)),
    /* e6 */ InstrCycle(todo_opcode!(0xe6)),
    /* e7 */ InstrCycle(todo_opcode!(0xe7)),
    /* e8 */ InstrCycle(inx_cyc1),
    /* e9 */ InstrCycle(todo_opcode!(0xe9)),
    /* ea */ InstrCycle(nop_cyc1),
    /* eb */ InstrCycle(todo_opcode!(0xeb)),
    /* ec */ InstrCycle(todo_opcode!(0xec)),
    /* ed */ InstrCycle(todo_opcode!(0xed)),
    /* ee */ InstrCycle(todo_opcode!(0xee)),
    /* ef */ InstrCycle(todo_opcode!(0xef)),
    /* f0 */ InstrCycle(todo_opcode!(0xf0)),
    /* f1 */ InstrCycle(todo_opcode!(0xf1)),
    /* f2 */ InstrCycle(todo_opcode!(0xf2)),
    /* f3 */ InstrCycle(todo_opcode!(0xf3)),
    /* f4 */ InstrCycle(todo_opcode!(0xf4)),
    /* f5 */ InstrCycle(todo_opcode!(0xf5)),
    /* f6 */ InstrCycle(todo_opcode!(0xf6)),
    /* f7 */ InstrCycle(todo_opcode!(0xf7)),
    /* f8 */ InstrCycle(sed_cyc1),
    /* f9 */ InstrCycle(todo_opcode!(0xf9)),
    /* fa */ InstrCycle(todo_opcode!(0xfa)),
    /* fb */ InstrCycle(todo_opcode!(0xfb)),
    /* fc */ InstrCycle(jsr_abs_ind_xind_cyc1),
    /* fd */ InstrCycle(todo_opcode!(0xfd)),
    /* fe */ InstrCycle(todo_opcode!(0xfe)),
    /* ff */ InstrCycle(todo_opcode!(0xff)),
];
