name: R-SNES

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/G-EIP-600-NAN-6-1-eip-florent.charpentier.git"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fetch
        uses: actions/checkout@v5.0.0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.90.0

      - name: Check program compilation
        timeout-minutes: 3
        run: cargo check --workspace

  coverage:
    needs: [check_program_compilation]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fetch
        uses: actions/checkout@v5.0.0

      - name: Cache/Uncache cargo tarpaulin
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-tarpaulin

      - name: Install rust
        uses: dtolnay/rust-toolchain@1.90.0

      - name: Install cargo-tarpaulin if not cached
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin
          fi

      - name: Run coverage
        run: cargo tarpaulin --out html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.ref_name }}
          path: ./tarpaulin-report.html


  push_to_mirror:
    needs: [coverage]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout fetch
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
