name: Gihub Pages Deploy

on:
  workflow_run:
    workflows: [R-SNES]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # Run only if R-SNES build succeeded and is on "main" branch
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          (github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Uncache coverage report
        uses: actions/cache@v4
        with:
          path: ./tarpaulin-report.html
          key: coverage-report-${{ hashFiles('./tarpaulin-report.html') }}
          restore-keys: coverage-report-

      - name: Prepare site for deployment
        run: mv ./tarpaulin-report.html ./site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
